### ISSUE TITLE
How can you detect Remote operations ?

### ISSUE THREAD

**Issue by shaunreinson** [fetchbot/node-red-contrib-ikea-home-smart#16]
The remote device type has no 'observe' tick, and whilst I can request a status from Blind (for drop and/or battery) I can't seem to request anything from Remote.

Main reason for doing this is to get a battery reading from it....

Am I missing something, or is the plugin ?

**Comment by shaunreinson** [comment]
OK, got it now - inject a status payload and it comes out. Obvious really, RTFM...

**Comment by jonasCr** [comment]
Hi @shaunreinson,
Can you explain a bit more about how you did it ? I'm quite new to node-red and a bit lost. I'm able to get the data of the remote from the payload but not much more :(.

**Comment by shaunreinson** [comment]
Use the inject node to pass a 'status' into the Ikea-homesmart node on the Remote you want details of.

So msg.payload = "status" on the Inject node

Inspect the msg.payload that results to extract what you (I just wanted battery which is msg.payload.deviceInfo.battery)

I used a Function node which, because I was passing into InfluxDB said:

var name=msg.payload.name;
var bat=msg.payload.deviceInfo.battery
msg.payload={location:name, battery:bat}
return msg

If you just want the payload to be Battery then just edit the above.
