### ISSUE TITLE
Detect button pressed on remote

### ISSUE THREAD

**Issue by quimzinho** [fetchbot/node-red-contrib-ikea-home-smart#22]
Hello,
Is it possible to detect when I press one of the 4 buttons to trigger some events in node red?
If yes is it possible to differenciate duration (short/long)?

Thanks

**Comment by Urs-Eppenberger** [comment]
I have exactly the same question. The IKEA Tradfri dimmer buttons would be a nice remote control for my home automation. And the buttons are accepted by my wife, which is a great plus.
Did you hear anything back?

There is the possibility to select 'observe device' for bulbs and for groups. It disappears if you select a dimmer/remote.
Clever as I am, I thought in that case I pair the dimmer with a light bulb and observe this. Nope.
The 'observe device' option seems not to work anyway in my case.

I finally gave up and ordered a zigbee USB stick. Together with the zigbee2mqtt software I might be able to solve this if I understood the webpages correctly. We'll see.
