### ISSUE TITLE
Will this also work with a Philips Hue Bridge?

### ISSUE THREAD

**Issue by oxivanisher** [fetchbot/node-red-contrib-ikea-home-smart#6]
I currently have a Philips Hue Bridge, which also works on the ZigBee protocol like the IKEA ones. I would rather not buy also a IKEA TRÅDFRI Gateway if the Philips one works also. If I have a look at the configuration settings, it is not clear to me if the "Pre-shared key" is the same as the API Key:

Philips Hue Bridge node settings:
![image](https://user-images.githubusercontent.com/264994/74667861-5cb3e000-51a4-11ea-981f-ae9f08a0c5a1.png)

node-red-contrib-ikea-home-smart settings:
![image](https://user-images.githubusercontent.com/264994/74668292-39d5fb80-51a5-11ea-9e92-a953869d4044.png)
Can somebody shed some light on this? Thanks!

**Comment by mvujica** [comment]
This palette is not intended for Hue bridge, only for Ikea, please use other nodes, not from this developer like: https://flows.nodered.org/node/node-red-contrib-huemagic

**Comment by oxivanisher** [comment]
Thanks for the information. Since I want to control the smart blinds, the hue bridge probably won't work. 🤷‍♂ Luckily, the gateway is not as expensive as the hue bridge was. ;)
